### ISSUE TITLE
Contact.smartystreets__Mailing_Time_Zone__c field removal from managed package

### ISSUE THREAD

**Issue by alpha-bytes** [ToAFinish/addressverification#7]
In version `6.5.6` of the managed package it states that the field `Contact.smartystreets__Mailing_Time_Zone__c` has been removed from the package definition:
> This Custom Field Definition has been removed from the managed package. You can delete the component if no longer needed.

It appears that data is still being populated to this field, however. Can you confirm whether this was a mistake or if there are plans to deprecate the persistence of timezone data in the future?

**Comment by ToAFinish** [comment]
There is no plan to stop timezone data from being available.  This should be available going forward.

This is merely one of the many fields that were removed from the package in order to cut down on the number of fields that are installed with the package.  If you install the package now, you will need to create the field yourself, and map it.

**Comment by alpha-bytes** [comment]
Got it, thanks so much for the quick resolution!
